### ISSUE TITLE
which user manual text is most up to date?

### ISSUE THREAD

**Issue by bruhwiler** [zhanghe9704/electroncooling#1]
Which of these two links is best?

https://github.com/zhanghe9704/electroncooling/blob/master/User%20manual.md

or

https://github.com/zhanghe9704/electroncooling/blob/master/JSPEC%20User%20Manual.pdf

or are they kept synchronized?

Thanks!
David

**Comment by zhanghe9704** [comment]
The second one. I think the first one has been removed.

Best,
He

He Zhang
Computational Accelerator Physicist
Center for Advanced Science of Accelerators
Jefferson Lab
(O) 757-269-6657
(Cell) 517-896-3293
www.hezhang.us
