### ISSUE TITLE
Force units?

### ISSUE THREAD

**Issue by sjcrs** [zhanghe9704/electroncooling#6]
I am trying to understand the units of the force calculation within the Parkhomchuk model. I know that Betacool returns a numerical value for the frictional forces in terms of eV/m, but the Betacool physics guide also uses a different set of terms in the force calculation. What is the difference between the Betacool F_const (as shown in the Betacool physics guide) and what is shown here:

`double f_const = -4*k_c*k_c*k_ke*k_ke*k_e*k_e*k_e/(k_me*1e6);`

When I try to compare forces return from both JSPEC and Betacool I find they are different by a factor of roughly 25/k_e.

**Comment by zhanghe9704** [comment]
The unit of the force is Newton. The formula comes from "New Insights in the theory of electron cooling" by V.V. Parkhomechuck. "k^2, where k = 1/(4*pi*epsilon_0)" is added to the coefficient. I believe it's needed if you want to use the SI unit in the formula. 
An email with more details has been sent to you.
