### ISSUE TITLE
Benchmarking against Betacool

### ISSUE THREAD

**Issue by sjcrs** [zhanghe9704/electroncooling#8]
Hi,
Using your master branch, I've constructed an ecooling example comparable to an EIC design. The parameters are:

            //define coasting gold beam in an EIC scenario
            int n_charge = 79;
            double n_mass = 197;
            double kinetic_energy = 1e5*n_mass;
            double gamma = 1+kinetic_energy/(n_mass*k_u);
            double beta = sqrt(1-1/(gamma*gamma));
            double emit_nx0 = beta*gamma*5e-6;
            double emit_ny0 = beta*gamma*5e-6;
            std::cout<<std::endl;
            std::cout<<"gamma ="<<gamma<<" beta ="<<beta<<" emit_nx0="<<emit_nx0<<std::endl;
            double dp_p0 = 0.004;
            double n_ptcl = 5E8;
            double sigma_s_ion = 2e-2;
            Beam c_beam(n_charge, n_mass, kinetic_energy, emit_nx0, emit_ny0, dp_p0, sigma_s_ion,n_ptcl);

            //define the ring
            std::string filename = "Booster.tfs"; 
            Lattice lattice(filename);
            Ring ring(lattice, c_beam);

            //define the cooler
            double cooler_length = 1;
            double n_section = 1;
            double magnetic_field = 5;
            double beta_h = 10;
            double beta_v = 17;
            double dis_h = 0;
            double dis_v = 0;
            Cooler cooler(cooler_length,n_section,magnetic_field,beta_h,beta_v,dis_h, dis_v);

            //define electron beam
            double current = 0.03;
            double radius = 0.025;
            double neutralisation = 0;
            UniformCylinder uniform_cylinder(current, radius, neutralisation);
            double gamma_e = c_beam.gamma();
            double tmp_tr = 0.05;
            double tmp_long = 0.1;
            EBeam e_beam(gamma_e, tmp_tr, tmp_long, uniform_cylinder);

            //define cooling model
            unsigned int n_tr = 100;
            unsigned int n_long = 100;
            EcoolRateParas ecool_rate_paras(n_tr, n_long);

            ForceParas force_paras(ForceFormula::PARKHOMCHUK);
            double rate_x, rate_y, rate_s;
            ecooling_rate(ecool_rate_paras, force_paras, c_beam, cooler, e_beam, ring, rate_x, rate_y, rate_s);

I've also constructed the same situation for comparison in BETACOOL. The comparison of forces is shown below:
![image](https://user-images.githubusercontent.com/55888605/74290492-41059100-4cef-11ea-933b-1a06f85dd6b2.png)

I'm wondering if you benchmarked against Betacool in your development. It's possible I made a mistake with the Betacool configuration.

**Comment by zhanghe9704** [comment]
Benchmark with betacool has been done for IBS rate, cooling rate, and beam parameter envolving using the RMS dynamic model and the particle model (model beam in betacool) respectively. Some of the benchmarking results are published in previous conference papers on jspec. I didn't benchmark for friction force, because I don't know which unit betacool uses in force calculation and I think the above benchmarking is enough. I can send you some of my benchmarks if you're interested.

**Comment by sjcrs** [comment]
Please do send me the conference papers so I can duplicate some of your checks. I now think my problem is likely an improper Betacool configuration, which is unfortunately easy to do. Thank you!
